name = "shareplz-server"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# Durable Objects 설정
[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v4"
new_classes = ["Room"]
deleted_classes = ["Counter"]


# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB"
database_name = "shareplz-db"
database_id = "4ffb1ac9-bad6-4cd1-bd50-9b56860cb21c"
